### ISSUE TITLE
'Failed to load article from page' when entering Reader View via wikipedia.org

### ISSUE THREAD

**Issue by adalucinet** [mozilla/readability#148] opened 2015-04-16 13:43 UTC
Affected branches:
Beta 38.0b4 (20150415030206), Aurora 39.0a2 (2015-04-16) and Nightly 40.0a1 (2015-04-15)

Sample page showing this issue:
http://en.wikipedia.org/wiki/Phoenicia

**Comment by gijsk** [comment] 2015-04-16 13:47
Dupe of #138

**Closed by gijsk** 2015-04-16 13:47 UTC
