### ISSUE TITLE
Publish Readability.js on npmjs.com

### ISSUE THREAD

**Issue by evanxd** [mozilla/readability#361] opened 2017-03-07 11:36 UTC
I think we could publish Readability.js on npmjs.com. That will help other developers reuse 
Readability.js in their projects easier and faster. The module name could be `mozilla-readability` since the `readability` module name is already taken.

What do you think? @gijsk

**Comment by gijsk** [comment] 2017-03-07 13:00
This is a duplicate of #43 . The main issue is that we shouldn't publish this under our personal github username, and I don't know how to / don't have contacts for the people involved with / to publish it publicly under the mozilla org.

**Closed by gijsk** 2017-03-07 13:00 UTC

**Comment by backflip** [comment] 2017-12-31 21:25
@dherman, could you help publish this repository by any chance? You seem to be the maintainer of https://www.npmjs.com/~mozilla
