### ISSUE TITLE
Problem with readabilty function in firefox.

### ISSUE THREAD

**Issue by Fabio64PG** [mozilla/readability#602] opened 2020-07-06 11:04 UTC
I am using firefox 78.0.1 and I am e blind!
I, initially, found this problem only with the Zeus news site,

www.zeusnews.com

 but, for a few days, I have had the opportunity to also check with other sites and I have had the same problem in other sites precisely.
Here is the problem:

- opened the site,
- being complex to read the required piece,
   for frame etc .;
- Well, from the menu displays,
- I choose, as always, reading mode;
- here I have the surprise;

generally, the comparison of the page for reading the piece, with the
cursor, almost always, already positioned at the beginning, ready to be read.
For a few days, having checked the reading mode, I have only found the buttons

- disable reading,
- listen
- and another that I don't remember.

Unfortunately, nothing appears of the text and I cannot even listen to the text.

   Why do I have this problem?
Is this a problem with the version of firefoX I use?
How can I solve it?

   Thanks for the answer that I can have.

**Comment by gijsk** [comment] 2020-07-06 14:28
@eeejay, do you know what could be going on here?

Reporter: what screenreader do you use?

**Comment by gijsk** [comment] 2020-07-06 21:48
Ah, some help in the Accessibility channel on Mozilla's matrix server has helped clarify what the issue is.

This github repo is about the readability library (which handles extracting the reader mode content from the original webpage) and the bug you reported is specific to the way in which Firefox uses this library, so I'm going to close this report -- but I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1650922 on your behalf and have put up a patch so we can fix this in Firefox ASAP.

**Closed by gijsk** 2020-07-06 21:48 UTC
