### ISSUE TITLE
"Failed to laod article from page" on long page at astronomy.com

### ISSUE THREAD

**Issue by msujaws** [mozilla/readability#512] opened 2019-01-28 15:23 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1522783,

"On an article on astronomy.com, for example this one, enabling Reader Mode results in a large "Failed to load article from page" error."

URL: http://www.astronomy.com/news/2018/11/ultra-bright-galaxy-feeds-its-black-hole-by-ripping-material-from-neighbors

I have reproduced this on Nightly 66.0a1 (2019-01-22) (64-bit).

**Comment by gijsk** [comment] 2019-01-28 15:33
This is caused by the `<meta>` tag that doesn't have a `content` attribute.

See e.g. this example: https://output.jsbin.com/yuxabosili/ .

This is trivial to fix by adding some falsy-checks for `content` to the relevant parsing code in https://github.com/mozilla/readability/blob/878545f64d4cc389bbc4031a130ccbaf425c7211/Readability.js#L1209

**Comment by gijsk** [comment] 2019-01-28 15:56
Fixed by #513 .

**Closed by gijsk** 2019-01-28 15:56 UTC
Labels: has-website-testcase, reader-mode-has-issues
