### ISSUE TITLE
Adjacent tags result in merged text.

### ISSUE THREAD

**Issue by timlib** [mozilla/readability#939] opened 2024-12-30 22:55 UTC
If the page has source as such:

`<h3>Foo</h3><p>Bar</p>`

It will be rendered in the browser as two different words, as intended by the markup.  Below I have pasted as non-code and you can see how it looks:

<h3>Foo</h3><p>Bar</p>

However, the "textContent" field of Readability will merge the words as: "FooBar", which is incorrect.

My long-standing solution has been to parse the "content" HTML data of Readability, which works, but adds another layer of non-trivial code maintenance and effort.

I am wondering if there is a solution to this problem?  This has been a bug since the Arc days, I've always wondered if anybody else was dealing with it.

**Comment by gijsk** [comment] 2024-12-31 14:44
This is a duplicate of #779  which has more context on this problem.

**Closed by gijsk** 2024-12-31 14:44 UTC

**Comment by timlib** [comment] 2025-01-16 19:35
I'm not sure why this is a WONTFIX bug, it undermines the core utility of the textContent functionality.  If there is no intention for textContent to produce actual text content it should be removed as the current situation introduces a very subtle bug most people won't notice immediately.  It's much worse to have it exist and be subtly broken, than to not have it at all.

I'm going to open a new issue to remove textContent from Readability.js as that is the best solution.
