### ISSUE TITLE
Popular Mechanics

### ISSUE THREAD

**Issue by davidar** [mozilla/readability#379] opened 2017-05-07 06:29 UTC
Readability is missing large chunks of text, for instance on [this article](http://www.popularmechanics.com/science/health/a26038/the-blood-of-the-crab/) only the last ~25% is extracted. It looks like the page is broken into a number of sections (for ad placement) wrapped by

```html
<div class="longform-article-body--container longform-article-body--container-main">
  <div class="longform-article-body--content">...</div>
</div>
```

and readability is only picking up a single one of those sections.

**Comment by andreskrey** [comment] 2017-12-10 11:26
Could not reproduce, article gets parsed correctly. There are a few nodes that could be removed ("advertisement, please continue reading below") but all the relevant text is there.

I think it's safe to close this issue.

**Comment by gijsk** [comment] 2017-12-11 14:01
I'm seeing the same as the previous comment, so I'm going to go ahead and close this. :-)

**Closed by gijsk** 2017-12-11 14:01 UTC
