### ISSUE TITLE
request addition to README: guide for website makers

### ISSUE THREAD

**Issue by mlda065** [mozilla/readability#502] opened 2018-12-19 23:08 UTC
I'm trying to make a website, and it's not currently readable by readability.

I would find it very helpful if there was a guide in the README (or elsewhere) with a checklist of things webmasters should do to make their website readable.

E.g. things I've already tried:
* check the syntax is valid with the [W3C validator](https://validator.w3.org/)
* Keep the DOM tree shallow in the body of the content
* Use `<aside>`, `<header>` etc

Other questions which such a checklist should say:
* Do I need to add `id`s to my elements? 
* Do I need a `<section>`? 
* Is readability penalising me for a `<pre><code>content</code></pre>` element?

My site is super simple hand-crafted html. No bloat, no margins, no navigation menu, no footer, no ads. 
I've found a few other super-simple sites which have very unambiguous content , e.g. [The Mother f-ing Website](https://motherfuckingwebsite.com/) and most of [stallman.org](https://stallman.org/apple.html). 

It would be great to document why readibility can't parse such simple pages, but it can parse bloated news sites.

**Comment by gijsk** [comment] 2018-12-20 16:00
There are 2 parts to this. 

1 is whether Firefox shows a "open in reader mode" icon. That mostly depends on whether it can find enough textual content in `<p>` and/or `<div>`-with-`<br>` tags (the algorithm lives here: https://github.com/mozilla/readability/blob/876c81f710711ba2afb36dd83889d4c5b4fc2743/Readability.js#L1707-L1764 - it's fairly straightforward). That algorithm ignores content in tags that have classnames or ids that match items in a list of negatively-associated terms (to do with ads or such, mostly). The issue with these pages is likely that there isn't enough content to trip that algorithm to decide it's worth offering reader mode. Lowering the threshold would likely cause it to show up in situations where that is unexpected / not useful, like on any old page on corporate websites that have a lot of legalese stuck in a footer somewhere. We could consider making it proportional to the size of the page, but then the problem becomes how to measure that in a way that isn't CPU-intensive, as the detection should be very fast.

The second portion is whether reader mode works. For that, it mostly depends on finding a single container element that contains all the 'relevant' content. The one concrete page you gave as an example here doesn't work - I'm not sure why off-hand, but you can run readability locally fairly easily with debug mode turned on, and that'll tell you. It's possible that the content is so spread out (ie lots of 1-sentence paragraphs with headers in the middle) that the more elaborate algorithm can't find a cohesive set of text, either. However, e.g. https://stallman.org/microsoft.html works with reader mode, which you can see by putting: `about:reader?url=https://stallman.org/microsoft.html` in the URL bar in Firefox. It likely doesn't get picked up with reader mode because that doesn't look for list items, and Stallman doesn't really write prose here but lists, which again on bigger sites are easily filled with useless "related article" spam or such like.

On the whole, I think there isn't an easy way to write the type of document you want here. Coming up with a list of "here are things readability looks for", beyond semantic HTML and "sufficient amounts of prose", in some form or another, is liable to abuse by websites (ie websites could easily manipulate the list of terms we look for in ids/classes if they were so inclined), doesn't really help for the "make the reader mode icon show up" question that you're effectively asking about, and is also likely to quickly be outdated as/when changes are made. Readability is very much not a standard, just an improvised, kludgy way of making sense of an improvised, kludgy internet/web. Other people are working on other ways to do that (e.g. Safari, Pocket, etc. ) and there's no guarantee that Firefox's implementation won't change. Overly specific documentation would risk seeming to guarantee that "if you do X and Y, reader mode will work", when we can give no such guarantee for any length of time.

Without seeing the actual website that you're working on, I'm afraid I don't really have other advice to offer. On the whole, the concrete request for documentation is a duplicate of #9 .

**Closed by gijsk** 2018-12-20 16:00 UTC
Labels: has-website-testcase, reader-mode-has-issues, should-be-readerable
