### ISSUE TITLE
Unordered lists are displayed as ordered lists

### ISSUE THREAD

**Issue by alexgibson** [mozilla/readability#93] opened 2015-04-02 10:34 UTC
I noticed that unordered lists `<ul>` get displayed numerically in Reader View, as though they we're ordered lists `<ol>`. You can observe this in the following article by toggling into Reader View:

http://alistapart.com/article/taminglists/

I think it would perhaps make sense for the default styling for an unordered list to use a disc instead?

**Comment by gijsk** [comment] 2015-04-02 10:43
This should really be in bugzilla as the stylesheet isn't in this repo... or perhaps we should move the stylesheet? :-\ @leibovic - we also seem to have two different files with similar content for android and desktop, which I guess we should fix?

Finally, I swear I've seen this reported before, just can't find the bug / github issue.

The cause is aboutReader.css in mozilla-central saying these should be "disk" when it should be "disc".

**Comment by alexgibson** [comment] 2015-04-02 11:03
I'll file an equivalent bug over on bugzilla, thanks

**Comment by alexgibson** [comment] 2015-04-02 12:09
Opened [bug 1150476](https://bugzilla.mozilla.org/show_bug.cgi?id=1150476)

**Comment by gijsk** [comment] 2015-04-02 12:20
Thanks! Fixed on fx-team, so closing this. Will be in tomorrow's nightly.

**Closed by gijsk** 2015-04-02 12:20 UTC

**Comment by leibovic** [comment] 2015-04-02 15:50
@gijsk thanks for the quick fix here! I've talked with @st3fan in the past about making a shared content style sheet that lives in this repo, but for the short term we decided to stick with different styles for desktop/mobile, since there were some discrepancies in the specs.
