### ISSUE TITLE
Best practice

### ISSUE THREAD

**Issue by runxel** [mozilla/readability#553] opened 2019-08-03 13:49 UTC
You should make a "Best practice" guide for web devs, so we can optimize our websites.

---
(Like on a personal site Readability will always give me just the site's name, instead of the blog article title as title. I even looked in the code but I can't figure out why Readability trips... 🙄)

**Comment by gijsk** [comment] 2019-08-15 14:41
Without a link it's hard to give advice about the title, but I suspect it has to do with the metadata the page includes using graph/twitter/whatever tags being wrong.

Generally, the algorithm changes and in the past I haven't thought it particularly useful to try to document it, because it'll just change over time and then people will be upset that it "stopped working". The general guideline is "use standards-based markup", ie use `<p>` tags for paragraphs, `<h1/h2/h3>` etc for headings, and so on. Generally speaking that should be enough. I also worry about giving too much advice which would then be used by big publishers to create very unreader-able content on purpose, to avoid people using it and them losing advertising revenue.

**Comment by runxel** [comment] 2019-08-25 12:44
The site's just local for the moment, therefore no link, sorry.
While I understand that you don't want to give hints to the big publishers its also quite strange to observe this behaviour of «look, theres a mystical thing and nobody shall know how it works. Take it as a miracle!».... 

But back to topic:
The markup is fairly simple and I'm just using vanilla HTML, none of that third-party garbage.
```html
<!doctype html>
<html lang="en">
<head>
    <title>NOT WHAT I WANT</title>
</head>
<body>
<header class="header">
	<a class="logo" href="#">THIS NEITHER</a>
	<nav>…</nav>
</header>
<main>
    <article>
        <header>
            <h1>THIS IS IT</h1>
            <time class="note-date">27 July 2019</time>
        </header>
         <section> … </section>	
    </article>
</main>
<footer class="footer"></footer>
</body>
</html>
```

What I want is that the one and only `<h1>` on my page should be taken into account. – Not the `title` in head.... :/
Any way to change that? I'm happy for every hint.

**Comment by gijsk** [comment] 2019-08-26 10:54
>  Any way to change that? I'm happy for every hint.

https://github.com/mozilla/readability/blob/master/Readability.js#L1267-L1278

https://github.com/mozilla/readability/blob/master/Readability.js#L360

We prefer page metadata, and if none is present, then the `<title>` over trying to scrape headers (which unfortunately are often not used in semantically correct ways, cf. https://github.com/mozilla/readability/issues/281 ). There's also the straight bug https://github.com/mozilla/readability/issues/464 which may affect your case (unsure off-hand).

Finally, I just realized that this is a dupe of https://github.com/mozilla/readability/issues/9 so I will close this issue...

**Closed by gijsk** 2019-08-26 10:54 UTC
Labels: maintenance
