### ISSUE TITLE
JSDOMParser errors on http://www.newyorker.com/magazine/2014/12/01/quiet-german

### ISSUE THREAD

**Issue by leibovic** [mozilla/readability#77] opened 2015-03-25 00:27 UTC
```
JSDOMParser error: expected '</lineargradient>'
JSDOMParser error: expected '</defs>'
JSDOMParser error: expected '</svg>'
JSDOMParser error: expected '</h1>'
JSDOMParser error: expected '</div>'
JSDOMParser error: expected '</div>'
JSDOMParser error: expected '</div>'
JSDOMParser error: expected '</div>'
JSDOMParser error: expected '</div>'
JSDOMParser error: expected '</body>'
JSDOMParser error: expected '</html>'
```

**Comment by n1k0** [comment] 2015-03-25 07:23
This is fun, trying to create a test case:

```
$ node test/generate-testcase.js germ http://www.newyorker.com/magazine/2014/12/01/quiet-german
JSDOMParser error: expected '</aside>'

JSDOMParser error: expected '</div>'

JSDOMParser error: expected '</div>'

JSDOMParser error: expected '</body>'

JSDOMParser error: expected '</html>'

No content generated by readability, not going to write expected.html!
```

**Comment by n1k0** [comment] 2015-03-25 07:26
In that case, the document indeed isn't well formed. I suspect we're preprocessing the HTML in some ways before passing it to the parser in FFx, hence our different results.

**Comment by DavidBruant** [comment] 2015-03-25 09:54
> In that case, the document indeed isn't well formed. I suspect we're preprocessing the HTML in some ways before passing it to the parser in FFx, hence our different results.

I don't understand this sentence. Why would readability pass the HTML string to Firefox? Firefox has its own parser.

In any case, misformed HTML is fairly common on the web. The HTML Living Standard defines how the DOM should look like when the markup is broken. Obviously browsers implement this behavior. I believe jsdom does it too (or at least, I imagine it's their goal).
At Mozilla, I think David Flanagan has experience writing a conformant parser, but I wonder if that's necessary at all. It's quite a tedious exercise.

**Comment by n1k0** [comment] 2015-03-25 10:07
> I don't understand this sentence. Why would readability pass the HTML string to Firefox? Firefox has its own parser.

Parsing is performed within a worker, where the DOM api isn't available; that's why JSDOMParser is used.

> Obviously browsers implement this behavior. I believe jsdom does it too

It does, though we're using JSDOMParser (which is !== jsdom), which is the only way I can think of to parse a DOM within a worker atm. If you know another lib capable of doing that in a more reliable manner, now is a good time to speak up :)

**Comment by gijsk** [comment] 2015-03-25 10:47
>> Obviously browsers implement this behavior. I believe jsdom does it too
> It does, though we're using JSDOMParser (which is !== jsdom), which is the only way I can think of to parse a DOM within a worker atm.

https://github.com/mozilla/readability/blob/master/test/generate-testcase.js#L93

It looks like jsdom doesn't help enough here, or something. I'd have to look at the actual HTML that's generating this error to figure out why.

**Comment by n1k0** [comment] 2015-03-25 11:00
BTW in FFX, what is used to preprocess the HTML content which is sent to the worker? Would it be conceivable to port/use this in our test env?

**Comment by gijsk** [comment] 2015-03-25 11:17
The actual DOM of the page is serialized using the XML serializer infrastructure in Firefox. That's all C++/XPCOM.

I don't think porting it is super-feasible in the short term. The best tradeoff I would be able to come up with would be writing an xpcshell script to do the work and invoking that from node via the commandline. Still doesn't sound particularly attractive in terms of how hard the script would be to write, and how clunky a solution that would be, though...

**Comment by DavidBruant** [comment] 2015-03-25 12:02
> In FFx, parsing is performed within a worker, where the DOM api isn't available; that's why JSDOMParser is used.

Given this is a Firefox feature, I imagine the worker is a chrome worker. Isn't there a way to access HTML parsing from a chrome worker? Not even via something like:
```js
var parserUtils = Components.classes["@mozilla.org/parserutils;1"]
                  .getService(Components.interfaces.nsIParserUtils);

parserUtils.parseFragment(htmlStr)
```
?

Another idea: If it's solely for the purpose of getting a DOM tree, could readability enable e10s and use/reuse an e10s tab to have the parsing in parallel?

> The actual DOM of the page is serialized using the XML serializer infrastructure in Firefox. That's all C++/XPCOM.

So the HTML is parsed then reserialized (via XML serializer infrastructure) in the main thread for the purpose of being parsed again in a worker?
On my machine, running the 22 test pages + JSDOMParser tests takes less than 500ms (a good share of that being HTML parsing), so extracting the core content of a page seems to be less than 20ms.
Is it really worth running Readability in a worker? Is the re-serialization overhead really worth it? Sure there will be always be some pathological cases where readability takes 20secs, but if the test pages are representative (and I believe they are), running readability in a worker seems more trouble than necessary.

**Comment by gijsk** [comment] 2015-03-25 12:06
> Given this is a Firefox feature, I imagine the worker is a chrome worker. Isn't there a way to access HTML parsing from a chrome worker? Not even via something like:

Workers (including Chrome Workers) have no access to the `Components` object and XPCOM in general. This is pretty obvious if you read https://developer.mozilla.org/en-US/docs/Web/API/ChromeWorker .

This was originally an android feature, and there the perf impact was deemed worth running this in a worker. That might not apply on desktop, but that doesn't fix the issue at hand.

**Comment by gijsk** [comment] 2015-03-25 12:07
Note also that the HTML isn't reparsed on the main thread for readability; the serializer just takes the page's actual DOM which is there already.

**Comment by gijsk** [comment] 2015-03-25 12:15
> Another idea: If it's solely for the purpose of getting a DOM tree, could readability enable e10s and use/reuse an e10s tab to have the parsing in parallel?

We can't selectively enable e10s for a single tab, and it's not ship-ready for 38, so that doesn't help us much here, sadly.

**Comment by DavidBruant** [comment] 2015-03-25 13:28
> This was originally an android feature, and there the perf impact was deemed worth running this in a worker. 

Where can I read about this? Given the need to re-serialize in the main thread, this is surprising.

> That might not apply on desktop, but that doesn't fix the issue at hand.

It would fix the issue at hand in the sense that removing the worker removes the need for JSDOMParser altogether and the bugs that come along with it (like this one).

**Comment by gijsk** [comment] 2015-03-25 13:38
>> This was originally an android feature, and there the perf impact was deemed worth running this in a worker.

> Where can I read about this? Given the need to re-serialize in the main thread, this is surprising. 

https://bugzilla.mozilla.org/show_bug.cgi?id=779796
@thebnich and @leibovic have a lot more context than me.

Note that on Android we ran this parse on every page load (to see if it was worth/possible offering reader mode), and we couldn't manipulate the real DOM because that'd obviously change the page, so there was a need to serialize+reparse *anyway*.

We don't do that anymore on desktop because doing that caused a boatload of perf regressions. So we have a simpler check that determines whether we show the button, which isn't 1:1 equivalent to whether the content is reader-able, but it's close. From that perspective, in principle we could reuse the DOM.

> It would fix the issue at hand in the sense that removing the worker removes the need for JSDOMParser altogether and the bugs that come along with it (like this one).

And it creates new issues, because currently Readability relies on JSDOMParser for e.g. turning `div` tags into `p` tags (by just assigning to `nodeName` which isn't how the real DOM works...) and relies on some other quirks. This is actually what I've been working on the last few days, and I almost have a patch ready, just need to work out my commit strategy.

**Comment by gijsk** [comment] 2015-03-25 13:58
Pushed that work as #78 .

**Comment by n1k0** [comment] 2015-03-27 14:47
So this page has this kind of markup (simplified):

```html
<aside id="footer-ad-google">
  <div class="ad" data-lazyad="" data-matchmedia="only screen and (min-width: 850px)">
    <script type="text/lazyad">
      <!--
        <script>…</script>
        <script src="foo.js"></script>
        </div>
      -->
    </script>
  </div>
</aside>
```

Will JSDOMParser ever be capable of dealing with such a thing? Do we **really** want it anyway?

**Comment by DavidBruant** [comment] 2015-03-29 16:24
> Will JSDOMParser ever be capable of dealing with such a thing?

comments + script element, what a delicious combo :-p

As said above, writing a standard compliant HTML parser is an extremely tedious exercise. jsdom uses [htmlparser2](https://www.npmjs.com/package/htmlparser2) which looks pretty solid. I haven't tried, but it's said to work with browserify, so it might work with [webworkify](https://github.com/substack/webworkify)?
I really discourage any attempt to write a new spec-compliant HTML parser in JS.

I derailled this thread with the idea that if Readability ran directly against the DOM Document in the tab (rather than in a web worker), it would remove the need for JSDOMParser altogether.
@gijsk, you said that it would add new issues because Readability doesn't work with a real DOM, but this should be fixed after #78 or #80. Are there other issues preventing running readability in the main thread?
I've read in a couple of places that Readability couldn't run against the main thread because of the risk of mutations, but I do not understand why. Readability can certainly run within a single event loop turn (preventing anyone else to modify the DOM) and the 20ms back-of-the-enveloppe measurement suggests it's largely acceptable in performance. Adding an article to the reading list is also rare enough an event that even a 1sec pause could be acceptable.

Can it be considered by Moz to not run Readability in a worker so the JSDOMParser dependency be removed (after #78 or #80 obviously)?

**Comment by gijsk** [comment] 2015-03-30 13:01
I think changing Readability to run on the main thread might be too big a risk for 38 which moves to beta today. @leibovic ?

**Comment by gijsk** [comment] 2015-03-30 13:07
FWIW, fixing JSDOMParser for this case shouldn't be *that* hard, I would have thought?

**Comment by DavidBruant** [comment] 2015-03-30 13:25
> I think changing Readability to run on the main thread might be too big a risk for 38 which moves to beta today.

I can agree. I believe our interests in this repo have different time scale. Whenever I say anything, really assume I mean "eventually". If your priorities require you to keep Readability in a worker for now, there is no problem. What I'm asking is whether it can be moved to the main thread at some point (even if that's after shipping Readability).
I'll file a bug on bugzilla and make it depend on reader mode shipping.

**Comment by DavidBruant** [comment] 2015-03-30 13:34
> I'll file a bug on bugzilla and make it depend on reader mode shipping.

https://bugzilla.mozilla.org/show_bug.cgi?id=1149138

**Comment by leibovic** [comment] 2015-03-31 13:40
Yes, I agree with @gijsk that we're focused on shipping Fx38 right now, and we can't afford to make such a big architectural change at this point.

FWIW, I think that iOS does run Readability.js on the main thread without JSDOMParser, so I think we could eventually move to this model for desktop/Android.

**Closed** 2015-04-01 10:45 UTC
