### ISSUE TITLE
Tests still passed even though some expected result doesn't valid anymore

### ISSUE THREAD

**Issue by RadhiFadlillah** [mozilla/readability#586] opened 2020-03-25 14:05 UTC
While I'm porting this library to Go, I realize that there are two test where its expected result doesn't valid anymore: `hidden-nodes` and `hukumusume`. To reproduce this issue, regenerate the test for those two case, then compare its result with the old one :

```
npm run generate-testcase hidden-nodes
npm run generate-testcase hukumusume
```

Here is the comparison for `hidden-nodes` :

<table>
    <tr align="center">
        <td><b>Current Expected Result</b></td>
        <td><b>Correct Expectation</b></td>
    </tr>
    <tr valign="top" align="center">
        <td width="50%"><a href="https://user-images.githubusercontent.com/6129042/77543716-a649c600-6eda-11ea-9bc6-68151b398672.png"><img width="350" src="https://user-images.githubusercontent.com/6129042/77543716-a649c600-6eda-11ea-9bc6-68151b398672.png"></a></td>
        <td width="50%"><a href="https://user-images.githubusercontent.com/6129042/77543830-cda09300-6eda-11ea-9298-08c216bbf5ce.png"><img width="350" src="https://user-images.githubusercontent.com/6129042/77543830-cda09300-6eda-11ea-9298-08c216bbf5ce.png"></a></td>
    </tr>
</table>

And here is comparison for `hukumusume` :

<table>
    <tr align="center">
        <td><b>Current Expected Result</b></td>
        <td><b>Correct Expectation</b></td>
    </tr>
    <tr valign="top" align="center">
        <td width="50%"><a href="https://user-images.githubusercontent.com/6129042/77544460-9979a200-6edb-11ea-84d9-b7846a33bba4.png"><img width="350" src="https://user-images.githubusercontent.com/6129042/77544460-9979a200-6edb-11ea-84d9-b7846a33bba4.png"></a></td>
        <td width="50%"><a href="https://user-images.githubusercontent.com/6129042/77544509-aa2a1800-6edb-11ea-8c4a-9adfb23511ef.png"><img width="350" src="https://user-images.githubusercontent.com/6129042/77544509-aa2a1800-6edb-11ea-8c4a-9adfb23511ef.png"></a></td>
    </tr>
</table>

For `hidden-nodes`, I don't know why the current expected result is valid because from what I understand the "third header" should never be removed. For `hukumusume`, the current expected result is not valid anymore since #579 is merged.

**Comment by gijsk** [comment] 2020-03-25 14:21
These are both differences at the end of the file/DOM; I expect the issue is that we compare the two DOMs by looping over the expected content and verifying it's present in the content produced by running the library. The fact that the latter produces extra content is then not flagged up.

**Comment by gijsk** [comment] 2020-03-25 14:49
the lwn testcase also seems to have a weird extra table cell...

**Comment by gijsk** [comment] 2020-03-25 15:02
#587 should fix this. Dunno why github hasn't picked it up automatically.

**Comment by gijsk** [comment] 2020-03-30 22:14
This should be fixed now.

**Closed by gijsk** 2020-03-30 22:14 UTC
Labels: maintenance
