### ISSUE TITLE
Reader mode not available of first load

### ISSUE THREAD

**Issue by btcrs** [mozilla/readability#592] opened 2020-05-01 15:12 UTC
When I open an [article on Wevolver.com](https://www.wevolver.com/article/2020.autonomous.vehicle.technology.report) in FireFox reader mode isn't initially available.

After toggling responsive design mode without navigating away from the page it then become available. I assume this is because of a rerender.

When does the check for readability happen on render? Is it possible the browser is still waiting on the call to the API and the entire page hasn't yet rendered?

**Comment by gijsk** [comment] 2020-05-04 15:33
It's super confusing, I know, so not your fault - but this is not really the best place for this report, as it's about the backend library we use. Firefox-specific bugreports are best put in bugzilla.mozilla.org , product Toolkit, component Reader Mode.

That said... I cannot reproduce (tested on current Firefox Nightly) - even if I toggle responsive design mode on and off again, I still don't see a reader mode icon being offered.

> When does the check for readability happen on render? Is it possible the browser is still waiting on the call to the API and the entire page hasn't yet rendered?

The check happens after the first paint event after `DOMContentLoaded`. If I had to guess (and, not being able to reproduce the responsive design mode issue, it's definitely a guess...) the problem is likely the opposite of what you suggest, ie we will maybe have checked before the majority of the content has loaded. It looks like the code fetches the article body using xhr/fetch, for a whopping 270kb JSON thing that includes a giant HTML blob that it then inserts. It'd make sense that without that content, no article is found.

Unfortunately, we cannot really reliably know when to check for readable content. We could add a second check, after the first paint after the `"load"` event has happened, but that might still not catch pages like this that load/add most of their content asynchronously... The readability check is not "free" to run, unfortunately, and we have to balance when we run it with not impairing page performance for non-reader-mode pages (e.g. causing skipped frames on video pages or in games). If you have good ideas on how to improve this, I'd definitely be open to hearing them!

**Comment by btcrs** [comment] 2020-05-04 17:14
Ah, gotcha. I appreciate you taking a look at in anyway. What you've mentioned seems to be the issue. That article is huge and almost fully asynchronously loaded, so at DOMContentLoaded the page is almost blank. The only thing I could see remedying the check would be looking into the contentful paints instead, but I'm not sure of the side affects from doing so.

Here's a gif showing the responsive design toggle:
![Screen Recording 2020-04-30 at 11 27 51 AM](https://user-images.githubusercontent.com/22106144/80993235-bc677200-8e08-11ea-9524-86fd9bb94f11.gif)

Probably best to move to bugzilla since the article is ultimately parsed without failure.

**Comment by gijsk** [comment] 2020-05-13 19:57
Thanks for filing https://bugzilla.mozilla.org/show_bug.cgi?id=1636150! Going to close this in favour of that ticket.

**Closed by gijsk** 2020-05-13 19:57 UTC
