### ISSUE TITLE
Lifehacker article missing lots of content

### ISSUE THREAD

**Issue by leibovic** [mozilla/readability#76] opened 2015-03-24 00:44 UTC
http://lifehacker.com/how-to-program-your-mind-to-stop-buying-crap-you-don-t-1690268064

**Comment by n1k0** [comment] 2015-03-24 08:30
I don't reproduce, [here's what I get](https://gist.github.com/n1k0/6d95cac6c5e2ddbba2ac); what's missing on your end?

I wish we get a much cleaner HTML, I'm actually finding that we're still including too much here :)

**Comment by n1k0** [comment] 2015-03-24 10:21
Just tested with latest fx-team, lots of contents missing indeed; though that's fixed entirely with updating the Readability.js version from latest master.

**Comment by leibovic** [comment] 2015-03-24 19:44
It's still not working for me on the latest fx-team, which includes the latest Readability.js changes. I wonder what could be happening differently for us.

**Comment by pdehaan** [comment] 2015-03-24 20:02
Here's what I see on
![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/6811568/0366841a-d226-11e4-9a4f-cedb507b95cd.png)

![how_to_program_your_mind_to_stop_buying_crap_you_don t_need](https://cloud.githubusercontent.com/assets/557895/6811564/fd0b9182-d225-11e4-916e-49ce27140f6a.png)

**Comment by pdehaan** [comment] 2015-03-24 20:07
I'm using today's FF Nightly, but is there any way to have Readability.js spit out a version number?
Or maybe we don't have some `Readability.VERSION` constant...

**Comment by pdehaan** [comment] 2015-03-24 20:23
I can't explain it, but it seemed to render fine/better in a different tab, but the original tab still shows the bad output and "Flagged". :uber_shrug:

![how_to_program_your_mind_to_stop_buying_crap_you_don t_need](https://cloud.githubusercontent.com/assets/557895/6811942/d59f9898-d228-11e4-8bf3-986321685c80.png)

**Comment by n1k0** [comment] 2015-03-24 22:02
I'm getting this (fx-team)

![screen shot 2015-03-24 at 22 59 38](https://cloud.githubusercontent.com/assets/41547/6813875/983b2a8e-d279-11e4-9342-204f17ea5431.png)

Now that's worrying if we all get different results… :x

**Comment by n1k0** [comment] 2015-03-24 22:06
OH reproduced your issue by opening the link several times in new tabs

![screen shot 2015-03-24 at 23 05 52](https://cloud.githubusercontent.com/assets/41547/6813963/6887828c-d27a-11e4-8e88-4eea1638b850.png)

Huuuuuuuuuh that doesn't sound good at all…

**Comment by n1k0** [comment] 2015-03-24 22:19
The *Flagged* html elements are 

```html
<p class="js_reply-flagged reply-flagged hide">Flagged</p>
```

I couldn't find this in original article html, so my suspicion is that it's generated by their js :/

**Comment by gijsk** [comment] 2015-03-25 20:20
Locally I made Firefox save a broken and working HTML bit for this page, but test-generate.js chokes on the broken case with actual errors (rather than producing the "wrong" output from the screenshot, as Firefox did). I haven't yet figured out how/why. :-\

**Comment by gijsk** [comment] 2015-03-25 20:21
(oh, and then I tried to pastebin these files so everyone could have a look, and `./mach pastebin` failed with encoding errors..)

**Comment by gijsk** [comment] 2015-03-30 18:38
The pull request seems to also fix the issue reported here, at least for me.

**Comment by n1k0** [comment] 2015-04-01 14:18
Using very latest Readability.js master in very latest fx-team, I'm now getting *XXX* for that URL with this error:

```
*************************
A coding exception was thrown and uncaught in a Task.

Full message: TypeError: node.parentNode is null
Full stack: Readability.prototype._grabArticle@resource://gre/modules/reader/Readability.js:545:13
Readability.prototype.parse@resource://gre/modules/reader/Readability.js:1594:26
Agent.parseDocument@resource://gre/modules/reader/ReaderWorker.js:48:12
worker.dispatch@resource://gre/modules/reader/ReaderWorker.js:21:24
anonymous/AbstractWorker.prototype.handleMessage@resource://gre/modules/workers/PromiseWorker.js:122:16
@resource://gre/modules/reader/ReaderWorker.js:35:41

*************************
```

**Comment by n1k0** [comment] 2015-04-01 14:22
Damnit, it seems to be intermittent :/

**Comment by gijsk** [comment] 2015-04-01 14:30
Are you using the latest `JSDOMParser.js` copy as well?

**Comment by n1k0** [comment] 2015-04-01 15:09
I've updated it and it seems to have fixed the parentNode issue, indeed :) 

I can still get the *Failed to load article from page* error randomly, for some other reason… Investigating it.

**Comment by n1k0** [comment] 2015-04-01 16:27
OK too hard to reproduce consistently, and when I do, the catch clause in `ReaderMode#_readerParse` is never visited. The only messages I could spot are:

```
Reader: Not parsing URI scheme: about
Reader: Reader mode disabled for URI
```

And as `parseDocument` returns null in such a case, the generic error message is displayed. Dunno if that's an actual issue, thoughts?

**Comment by gijsk** [comment] 2015-04-01 17:56
I mean, if we think the article should be reader-able, I would say it's an issue if we're returning null... can you pastebin / gist / "upload" a copy of the (Firefox-XML-serialized) HTML that's failing?

**Comment by n1k0** [comment] 2015-04-01 18:26
As I poorly tried to explain, in that case we're not even reaching the moment we're serializing the document, because `parseDocument` simply returns `null` if the URI scheme isn't supported. Which is annoying while you're trying to get readable content from a webpage (which isn't probably loaded just yet when this occurs, I suspect).

But maybe I don't properly understand the flow here?

**Comment by gijsk** [comment] 2015-04-01 20:15
`parseDocument` is the readability-invoking-bit. I want the stringified document it gets passed, ie `serializedDoc` from http://hg.mozilla.org/mozilla-central/annotate/e5b72a8edb82/toolkit/components/reader/ReaderMode.jsm#l248 .

**Comment by gijsk** [comment] 2015-04-01 20:17
More high-level, those error messages don't make a lot of sense... are these the things you're seeing when you're reproducing this? Because I didn't think that'd show the "failure" case - it basically implies we're trying to invoke reader mode either on `about:blank`/`about:newtab` which is loaded before the site is loaded, or on `about:reader` (ie we try to reader-ize the page twice or something). Neither of these should be happening...

**Comment by gijsk** [comment] 2015-04-14 17:29
This WFM on current trunk. @n1k0 can you clarify if this is fixed for you or not?

**Comment by n1k0** [comment] 2015-04-15 15:37
Hmm, nope, couldn't reproduce using very latest versions. I think we can safely close this.

**Closed by n1k0** 2015-04-15 15:37 UTC
Labels: has-website-testcase, reader-mode-has-issues
