### ISSUE TITLE
Readability does not treat same-page anchor links correctly

### ISSUE THREAD

**Issue by akashagrahari** [mozilla/readability#267] opened 2016-03-05 08:19 UTC
For webpages which have anchor points to subheading, readability alters the link which shows up in the final view.

For example - for the [link](http://jnb.ociweb.com/jnb/jnbJun2009.html)
[Thrift Architecture](http://jnb.ociweb.com/jnb/jnbJun2009.html#arch) becomes [Thrift Architecture](http://jnb.ociweb.com/jnb/#arch)

Screenshots
<img width="945" alt="screen shot 2016-03-05 at 6 31 09 pm" src="https://cloud.githubusercontent.com/assets/2344230/13547634/8e5902b4-e300-11e5-9217-3edfc07b2198.png">
<img width="815" alt="screen shot 2016-03-05 at 6 31 21 pm" src="https://cloud.githubusercontent.com/assets/2344230/13547635/8e5ae1ec-e300-11e5-8bcb-ea09a297198f.png">

**Comment by gijsk** [comment] 2016-03-07 09:54
Hm, odd. I can reproduce in the browser, but not with the base readability code in here. I tried modifying a builtin testcase, and it treats simple `href="#foo"` links correctly. I wonder what's broken...

**Comment by gijsk** [comment] 2016-03-07 10:16
Oh, after my test refactoring to use DOM methods we're not checking attributes, so that's why my testcase modification isn't catching that. That's silly of me. Anyway, now I have a failing test, just need to fix the issue now...

**Comment by gijsk** [comment] 2016-06-17 09:55
Woops, forgot to close this - but it's generating the correct markup now. Of course, now it seems we're still opening `#hash` links in Firefox against the original page in a new tab, which is only marginally better. But not a bug in readability.

**Closed by gijsk** 2016-06-17 09:55 UTC

**Comment by gijsk** [comment] 2016-06-20 11:51
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1280888 about the issue in Firefox.
