### ISSUE TITLE
Node is not defined

### ISSUE THREAD

**Issue by lazharichir** [mozilla/readability#414] opened 2017-12-04 22:22 UTC
Hello, just trying the package out but things aren't working as expected. I run it on `Node.js`.

	const jsdom = require("jsdom");
	const { JSDOM } = jsdom;
	const Readability = require('readability');

	process.on('unhandledRejection', r => console.log(r));

	//const url = 'https://engineering.linkedin.com/blog/2017/11/improving-resiliency-and-stability-of-a-large-scale-api';
	const url = "https://engineering.quora.com/Machine-Learning-Workshop-Combatting-Abuse-Online";

	JSDOM.fromURL(url).then(function( theDom ) {

		console.log(theDom.window.document.querySelector("p").textContent);
		console.log(theDom.window.document.querySelector("strong").textContent);

		var article = new Readability(url,theDom.window.document).parse();

		console.log(dom);
		console.log(article.title);
		
	});

This does give me a ReferenceError when executing it.

    My-MacBook-Pro:test-readability Lazhar$ node article.js --trace-warnings

    ReferenceError: Node is not defined
        at Readability._nextElement (/Users/My/Tests/gcf/test-readability/node_modules/readability/Readability.js:430:30)
        at Readability.<anonymous> (/Users/My/Tests/gcf/test-readability/node_modules/readability/Readability.js:455:27)
        at Proxy.forEach (<anonymous>)
        at Readability._forEachNode (/Users/My/Tests/gcf/test-readability/node_modules/readability/Readability.js:192:29)
        at Readability._replaceBrs (/Users/My/Tests/gcf/test-readability/node_modules/readability/Readability.js:445:10)
        at Readability._prepDocument (/Users/My/Tests/gcf/test-readability/node_modules/readability/Readability.js:416:12)
        at Readability.parse (/Users/My/Tests/gcf/test-readability/node_modules/readability/Readability.js:1712:10)
        at /Users/My/Tests/gcf/test-readability/article.js:22:60
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

I am pretty much following the examples both for JSDOM and Mozilla Readability so I am somewhat confused. Help would be appreciated!

**Comment by gijsk** [comment] 2017-12-05 13:17
If using `jsdom` you need to add a `Node` global, like e.g. in this sample: https://gist.github.com/bittlingmayer/15dfeb44e8b5108d1a3f5107d4adc50d#file-test-js-L17


This is effectively a dupe of #346 .

**Closed by gijsk** 2017-12-05 13:17 UTC

**Comment by gijsk** [comment] 2017-12-05 13:23
I've added a clarification to https://github.com/mozilla/readability#usage .

**Comment by backflip** [comment] 2017-12-31 21:10
@lazharichir I just installed the `readability-node@0.1.0` and `jsdom@11.5.1` on Node.js `8.2.1` and did not need a `Node` global. Which version were you running this on?
