### ISSUE TITLE
Embedded youtube videos not displayed

### ISSUE THREAD

**Issue by anthofo** [mozilla/readability#410] opened 2017-11-25 15:47 UTC
On most websites, the youtube videos are not displayed in the reader mode. The video iframe is always removed. For instance on: http://next.liberation.fr/culture-next/2017/11/24/screenshot-vape-wave-6-days-alphonse-president_1612047?xtor=rss-450

The following code
```
<p><iframe width="100%" src="https://www.youtube.com/embed/lGL7RgHn5f0" frameborder="0" allowfullscreen="" data-aspect-ratio="0.5625" data-responsive="1"></iframe></p>
```
is replaced by an empty p in reader mode:
```
<p></p>
```

**Comment by andreskrey** [comment] 2017-11-25 18:12
Could not reproduce with current version (as of https://github.com/mozilla/readability/commit/c2e370c2c7890e443a4b0c0eacaf8cb942ad201f)

It does happen on Firefox 57 reader view. So I guess there's something else happening after parsing the article and feeding it to the browser.

**Comment by paras7735** [comment] 2018-03-10 12:53
For https://www.vox.com/2017-in-review/2017/12/15/16751138/best-movies-2017 
it is doing the same.

**Comment by RadhiFadlillah** [comment] 2019-03-01 14:54
I've experienced this issue as well with https://www.rockpapershotgun.com/2019/03/01/the-flare-path-fogbound.

[](https://www.csie.ntu.edu.tw/~cjlin/libsvm/index.html)

I believe the problem is happened because in [`_cleanConditionally`](https://github.com/mozilla/readability/blob/master/Readability.js#L1619), we only check the `embed` tag, while the embedded videos usually found inside `iframe` or maybe `object`. In fact, that's how [`_clean`](https://github.com/mozilla/readability/blob/master/Readability.js#L1479) method filter which embed that must be deleted.

**Comment by gijsk** [comment] 2019-03-07 13:03
This is now fixed in readability. However, as noted in https://github.com/mozilla/readability/pull/526#pullrequestreview-209863785 , this won't be sufficient to fix this in Firefox due to security restrictions in Firefox.

**Closed** 2019-03-07 13:02 UTC
