### ISSUE TITLE
A bunch of stray bullets on thepostgame.com blog post (slideshow?)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/readability#97] opened 2015-04-03 22:30 UTC
### Steps to reproduce:
1. http://www.thepostgame.com/blog/list/201404/ultimate-warrior-dead-wrestlers-wrestlemania-vi-andre-savage-rude-hennig
2. Enter reader mode.
3. Scroll.
### Actual results:

A bunch of empty <li> tags.
### Expected results:

Not sure. No empty <li> tags, or an inline slideshow with images and whatnot.

---

![ultimate_warrior__one-third_of_wrestlemania_vi_competitors_now_dead](https://cloud.githubusercontent.com/assets/557895/6989897/6608905c-da16-11e4-8381-929bab5ddd3a.png)

**Comment by n1k0** [comment] 2015-04-04 16:22
This is even worse with latest versions of JSDOMParser+Readability:

![screen shot 2015-04-04 at 18 19 47](https://cloud.githubusercontent.com/assets/41547/6993520/3e5c075a-daf7-11e4-94ba-f8b46ab344b6.png)

It seems latest version simply considers the first image legend being the main readable content :(

**Comment by n1k0** [comment] 2015-04-04 16:28
Even more annoying:

```
$ node test/generate-testcase.js thepostgame http://www.thepostgame.com/blog/list/201404/ultimate-warrior-dead-wrestlers-wrestlemania-vi-andre-savage-rude-hennig
JSDOMParser error: Error reading attribute width, expecting '"'

JSDOMParser error: Error reading attribute height, expecting '"'

JSDOMParser error: Error reading attribute src, expecting '"'

JSDOMParser error: Error reading attribute ttp://geo.yahoo.com/b?s, expecting '"'

JSDOMParser error: Error reading attribute 146693317&t, expecting '"'

JSDOMParser error: expected '</noscript>'

JSDOMParser error: expected '</div>'

JSDOMParser error: expected '</div>'

JSDOMParser error: expected '</div>'

JSDOMParser error: expected '</div>'

JSDOMParser error: expected '</div>'

JSDOMParser error: expected '</div>'

JSDOMParser error: expected '</div>'

JSDOMParser error: expected '</div>'

No content generated by readability, not going to write expected.html!

https://api.virool.com/widgets/ba6280d?is_premium=1&ap=1&width=644&height=376&format=intext&fallback=1&widget_anchor=%23virool-widget-wrapper:4
?i.push(e):void 0},sendTo:function(e,t,n){return null==n&&(n="*"),e.postMessag
                                                                    ^
TypeError: Object [object global] has no method 'postMessage'
    at Object.VIROOL.PostMessage.sendTo (https://api.virool.com/widgets/ba6280d?is_premium=1&ap=1&width=644&height=376&format=intext&fallback=1&widget_anchor=%23virool-widget-wrapper:4:22458)
    at Object.VIROOL.PostMessage.sendToFrame (https://api.virool.com/widgets/ba6280d?is_premium=1&ap=1&width=644&height=376&format=intext&fallback=1&widget_anchor=%23virool-widget-wrapper:4:22611)
    at e.t.Inline.t.Inline.Loader.t.Inline.Loader.e.post (https://api.virool.com/widgets/ba6280d?is_premium=1&ap=1&width=644&height=376&format=intext&fallback=1&widget_anchor=%23virool-widget-wrapper:5:1576)
    at e.t.Inline.t.Inline.Loader.t.Inline.Loader.e.postViewabilityData (https://api.virool.com/widgets/ba6280d?is_premium=1&ap=1&width=644&height=376&format=intext&fallback=1&widget_anchor=%23virool-widget-wrapper:5:2858)
    at null.<anonymous> (https://api.virool.com/widgets/ba6280d?is_premium=1&ap=1&width=644&height=376&format=intext&fallback=1&widget_anchor=%23virool-widget-wrapper:5:3391)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

Note: we should probably **not** try to interpret remote JavaScript code!

**Comment by gijsk** [comment] 2015-04-06 17:10
What's triggering the JS execution here? Nothing in JSDOMParser ever does anything with JS... :-\

**Comment by gijsk** [comment] 2015-04-14 17:31
This WFM on current Nightly. @pdehaan is this still broken for you?

**Comment by pdehaan** [comment] 2015-04-14 19:18
@gijsk I... I actually don't know.

I have two tabs in Nightly with that same URL, and both render the content differently.
Note that the first screenshot (image 1) shows this (which is the first bulleted item in the list):

> _**Jim Hellwig**
> Ultimate Warrior foreshadowed his death on 'Raw' just a day after WrestleMania XXX: "Every man's heart one day beats its final beat. His lungs breathe their final breath. And if what that man did in his life makes the blood pulse through the body of others and makes them believe deeper in something that's larger than life, then his essence, his spirit, will be immortalized by the storytellers -- by the loyalty, by the memory of those who honor him, and make the running the man did live forever."_


---

![ultimate_warrior__one-third_of_wrestlemania_vi_competitors_now_dead_and_a_bunch_of_stray_bullets_on_thepostgame_com_blog_post__slideshow___ _issue__97_ _mozilla_readability_and_commits_ _mozilla-services_readinglist](https://cloud.githubusercontent.com/assets/557895/7145267/e62c9bde-e29f-11e4-8cec-6b2ad09e2365.png)

versus

![ultimate_warrior__one-third_of_wrestlemania_vi_competitors_now_dead](https://cloud.githubusercontent.com/assets/557895/7145276/f1825294-e29f-11e4-8e56-59fd007984d2.png)

---

### Original article:
![ultimate_warrior__one-third_of_wrestlemania_vi_competitors_now_dead___thepostgame](https://cloud.githubusercontent.com/assets/557895/7145321/49a9fd82-e2a0-11e4-8837-1b898f0b587d.png)

**Comment by gijsk** [comment] 2015-04-14 19:45
Weird... can you reproduce the half-cut-off version at all?

**Comment by pdehaan** [comment] 2015-04-14 21:02
@gijsk I just opened http://www.thepostgame.com/blog/list/201404/ultimate-warrior-dead-wrestlers-wrestlemania-vi-andre-savage-rude-hennig in 6 tabs in today's Nightly build, then switched to the reader mode. 2/6 tabs showed the truncated version, and 4/6 tabs showed the full version.

**Comment by gijsk** [comment] 2015-04-15 11:16
Huh. I can't reproduce this at all...

Can you repro in a new profile? Sounds like this has to do with the cookies in your profile and what ads you get served, or something. :-(

**Comment by pdehaan** [comment] 2015-04-15 18:38
I can still reproduce in a new profile w/ today's Nightly and  http://www.thepostgame.com/blog/list/201404/ultimate-warrior-dead-wrestlers-wrestlemania-vi-andre-savage-rude-hennig (where opening the URL in multiple tabs shows inconsistent results).

**Comment by pdehaan** [comment] 2015-04-15 18:47
I can also reproduce it on my main FF Beta profile where it shows the full scraped content 50% of the time (based on 4 tabs with the same URL).

But yes, re-reading your earlier comment, it may be ads based as I have funky ad setting in my /etc/hosts file:
```
127.0.0.1    widgets.outbrain.com
127.0.0.1    staticd.cdn.adblade.com
127.0.0.1    adblade.com
127.0.0.1    web.adblade.com
127.0.0.1    ad.doubleclick.net
127.0.0.1    static.newstogram.com
127.0.0.1    api.newstogram.com
127.0.0.1    ib.adnxs.com
127.0.0.1    video.ybpangea.com
```

If @n1k0 and @leibovic can't reproduce this issue then let's assume that I'm just an outlier and we can close this.

**Comment by pdehaan** [comment] 2015-04-15 19:07
And I tested in today's Aurora and it rendered the full content 1/6 times and the truncated content the other 5/6ths of the time.

But just to clarify, the original issue of stray bullets does seem fixed in all 3 browsers, this is just an issue of it rendering full or partial content.

**Comment by gijsk** [comment] 2019-03-25 12:28
This seems much better now, so I'm going to close this out. If there are still issues remaining with the site display, please file separate up-to-date issues. Thanks!

**Closed by gijsk** 2019-03-25 12:28 UTC
Labels: has-website-testcase, reader-mode-has-issues
