### ISSUE TITLE
h1 text elements not being extracted on medium.com

### ISSUE THREAD

**Issue by makeworld-the-better-one** [mozilla/readability#631] opened 2020-10-16 18:20 UTC
The following element was removed when going into reader mode in Firefox:

```html
<h1 id="5d1d" class="iz ja dm cd jb jc jd id je jf jg ih jh ji jj jk jl jm jn jo jp jq jr js jt ju ej" data-selectable-paragraph="">TEXT HERE</h1>
```

The `p` element at the same level, under the same `div`, was extracted.

```html
<p id="d7a2" class="hy hz dm ia b ib jv id ie if jw ih ii ij jx il im in jy ip iq ir jz it iu iv de ej" data-selectable-paragraph="">Text here</p>
```

This HTML was found on medium.com. I also experienced this bug when using readability-cli.

**Comment by gijsk** [comment] 2020-10-17 11:22
This is a duplicate of issue #464 .

**Closed by gijsk** 2020-10-17 11:22 UTC
