### ISSUE TITLE
All Wikipedia/BBC News/Other pages show only their title in reader mode

### ISSUE THREAD

**Issue by AaronMT** [mozilla/readability#237] opened 2015-07-16 14:16 UTC
Visit Wikipedia in Firefox for iOS and enter reader-mode, all pages fail.

![screen shot 2015-07-16 at 10 15 42 am](https://cloud.githubusercontent.com/assets/102331/8725686/a2d940b0-2ba3-11e5-9166-cb00844a83da.png)

**Comment by gijsk** [comment] 2015-07-16 14:42
Is this reproducible on android or desktop in some way? I don't have iOS available so it's hard to know what's wrong right now...

**Comment by AaronMT** [comment] 2015-07-16 15:04
No, this is filed against Firefox for iOS.

**Comment by wesj** [comment] 2015-07-16 15:17
I think we're locked at some random version of readability. Maybe we need to update?

**Comment by AaronMT** [comment] 2015-07-16 15:53
Can we figure that out and update?

**Comment by leibovic** [comment] 2015-07-16 23:10
AFAIK, mozilla-central has the latest Readability.js from here, but maybe we should start doing some sort of version tagging to make it easier for projects to incorporate stable versions. @gijsk, what do you think?

**Comment by gijsk** [comment] 2015-07-17 08:30
Happy to do that, though I'm not sure how many consumers we have beyond iOS...

**Comment by AaronMT** [comment] 2015-07-17 16:42
Another site with this issue, any article off of http://blog.twitch.tv

**Comment by rnewman** [comment] 2015-07-23 17:17
I see this repo and our Cartfile agree, we're pinned to `master`, and nothing has changed since May.

My Carthage checkout of Readability.js shows no diff versus the one in fx-team. So I think we're up to date, and this bug is in trunk and valid.

**Comment by leibovic** [comment] 2015-07-23 21:08
Can you get the raw HTML that you're parsing to create a testcase for us? Is it that Readability.parse() isn't returning anything? Showing "only the title" would be something that the reader view implementation is doing, not Readability itself.

**Comment by wesj** [comment] 2015-07-23 21:14
The problem here is that readability doesn't strip all ids/classes from the readable content. We're hitting some conflicts with our own Reader.html styles (specifically we set .content { display: none; } and then flip it to display: block once we have set up fonts and things). I wonder if Readability could strip all these attributes without breaking pages.

**Comment by leibovic** [comment] 2015-07-27 21:58
I don't know if it's an option for you, but we use scoped CSS styles for about:reader on desktop/Android. We specifically decided to do that to avoid this CSS selection collision. You could give your Reader.html ids/classes very specific names (e.g. .moz-reader-content).

**Comment by AaronMT** [comment] 2015-10-20 17:56
Wonder if this is related to what I see on Google. https://github.com/mozilla/readability/issues/253 - very bad readability

**Comment by gijsk** [comment] 2019-03-15 11:54
We now strip classes, so I'm going to close this. Please reopen if iOS still has issues here.

**Closed by gijsk** 2019-03-15 11:54 UTC
